name: tibiastalker
services:
  seq:
    image: datalust/seq:2023.1.9101
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - ${SEQ_PORT}:80
    volumes:
      - seq_logs:/data
    restart: unless-stopped
    networks:
      - tibia_stalker
    mem_limit: 400MB
    
#-------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_LISTENER_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_HOST_NAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER_NAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER_PASSWORD}
    volumes:
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/enabled_plugins
      # dont forget create "rabbitmq.config" with "[rabbitmq_shovel,rabbitmq_shovel_management]."
    restart: unless-stopped
    networks:
      - tibia_stalker
    mem_limit: 400MB
    
#-------------------------------------------
  postgres:
    image: postgres:16
    shm_size: 1gb
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - ./config/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tibia_stalker
    mem_limit: 2g
    
#-------------------------------------------
  tibia-data-api:
    image: ghcr.io/tibiadata/tibiadata-api-go:3.7.5
    container_name: tibia-data-api
    environment:
      - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - ${TIBIADATA_PORT}:8080
    restart: unless-stopped
    networks:
      - tibia_stalker
    mem_limit: 200MB

volumes:
  seq_logs:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local

networks:
  tibia_stalker:
    external: true
   # driver: bridge
# First you have to create network or comment "external" section and uncomment "driver" section
# docker network create tibia_stalker
