name: deploy
on:
  #push:
   # branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Run Build
        run: dotnet build --no-restore
        
      - name: Publish
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}
        
      - name: Build and publish Docker Images to GitHub Container registry
        uses: VaultVulp/gp-docker-action@1.6.0
        
  deploy-main:
    runs-on: ubuntu-20.04
    needs: build
    steps: 
      - 
